# Generated by Django 4.0 on 2024-01-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='Imagess/None/seample.jpg', upload_to='Images'),
        ),
    ]
