# Generated by Django 4.0 on 2024-01-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_movie_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='Images/None/seample.jpg', upload_to='Images'),
        ),
    ]
