# Generated by Django 4.0 on 2024-01-25 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.ImageField(default='https://www.google.fr/search?q=placeholder+image&tbm=isch&ved=2ahUKEwjuouCPsvmDAxWLXqQEHU0OABcQ2-cCegQIABAA&oq=placeholder+&gs_lcp=CgNpbWcQARgBMgQIIxAnMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEOgYIABAHEB46BAgAEB46BggAEAUQHlD1BljXEGCVH2gAcAB4AYABqwOIAbIQkgEJMC4yLjQuMS4xmAEAoAEBqgELZ3dzLXdpei1pbWfAAQE&sclient=img&ei=RsayZe7nOYu9kdUPzZyAuAE&bih=668&biw=1469#imgrc=vJkCGU5orcVcLM', max_length=500, upload_to=''),
        ),
    ]
